### PR TITLE
Update AboutView.vue

### PR DESCRIPTION
**Pull request by allella**
Replace CFG with HackGreenville and reword a few spots in the About page of the demo map

### CODE REVIEW

**Review by oliviasculley — APPROVED** [review]
I made sure to run the linter, but otherwise it looks great!

**Comment by allella** [comment]
Is something holding up the website build process?
https://github.com/hackgvl/open-map-data-multi-layers-demo/actions

because the live About page didn't change with this PR
https://hackgvl.github.io/open-map-data-multi-layers-demo/about

**Comment by oliviasculley** [comment]
Yeah, I think the next deploy will fix it. Let me cancel and restart, github actions occasionally does this

**Comment by oliviasculley** [comment]
Ok, it's updated now

**Pull request merged**
