### PR TITLE
fixes #29

### LINKED ISSUE #29: Create a 404 or Default Page
Create a default "catch-all" route for anything that doesn't match up with a view.

Current view of `/meow`:
Screenshot_2023-10-14_00-24-00

Maybe the default page could just be the map?

### PR DESCRIPTION
**Pull request by Alex-Grimes**
fixes #29 created a 404 page and added catchall route

### CODE REVIEW

**Comment by Alex-Grimes** [comment]
full screen 
image
and mobile 
image

**Comment by Alex-Grimes** [comment]
Found a intermittent issue in the e2e test for about where the click trigger was not actually happening really bizarre behavior honestly. Would consistently trigger and operate correctly with Dev tools open but not without them, Could also manually force the click that was supposed to be happening that was not on every run. added the Force option on the click and seems to behave more consistently now.

**Review by oliviasculley — APPROVED** [review]
This looks great, thank you especially for figuring out that weird cypress thing! Cypress can definitely be a bit finicky sometimes

**Comment by Alex-Grimes** [comment]
any chance of this getting merged in?

**Comment by ThorntonMatthewD** [comment]
@Alex-Grimes Yes! Sorry- I did not have notifications set up until recently on this repo. Thank you so much!

**Comment by oliviasculley** [comment]
@all-contributors add @Alex-Grimes for design and bugs :D

**Pull request merged**
