### PR TITLE
fixes #32

### LINKED ISSUE #32: Map tiles fail to load at max zoom
The maximum zoom on the map is [currently set to 20](https://github.com/hackgvl/open-map-data-multi-layers-demo/blob/711a57ac5df9b07bcd640a42dfa816de5d0a8347/src/components/MainMap.vue#L223), however at this zoom level the map tiles appear as solid grey images.

Screenshot_2023-10-16_20-00-39

You can see it in action here: https://hackgvl.github.io/open-map-data-multi-layers-demo/?lat=34.851224882536776&lng=-82.39967912435533&zoom=20&maps=free-wi-fi-hotspots

I'm wondering if the max zoom needs to be 18 instead since it seems to be inclusive.

### PR DESCRIPTION
**Pull request by Alex-Grimes**
updated the max zoom level for the current set of map tiles

### CODE REVIEW

**Comment by Alex-Grimes** [comment]
fixes #32

**Review by ThorntonMatthewD — CHANGES_REQUESTED** [review]
I've validated the change you've made! It looks great! :smile: 

What do you think about writing a Cypress test for the new limit? [This one ](https://github.com/Alex-Grimes/open-map-data-multi-layers-demo/blob/f44c87086ee9ae20af813b76fc0ae877a33d79a9/cypress/e2e/map.cy.ts#L37-L43) could be a good template, where the `deltaY`  for the scroll is set to something crazy like `-66.666666 * 50`, and there's a check to see that the url still only reports a `zoom=18`. This may be overkill, so please let me know if this feels kind of silly.

**Comment by Alex-Grimes** [comment]
Yeah should be no problem haven't worked with cypress so should be fun

**Comment by ThorntonMatthewD** [comment]
> Yeah should be no problem haven't worked with cypress so should be fun

Thank you! I hadn't used it before contributing to this project either, and it's pretty cool!

I'll be on standby to re-review and for any support.

**Comment by Alex-Grimes** [comment]
Added in the e2e test to confirm 18 is the max zoom now

**Review by ThorntonMatthewD — APPROVED** [review]
Thank you so much! LGTM!!!

**Comment by ThorntonMatthewD** [comment]
@oliviasculley Is it okay for this PR to be merged?

**Comment by oliviasculley** [comment]
Just FYI you're a maintainer now, so feel free :smile:

**Comment by oliviasculley** [comment]
@all-contributors add Alex-Grimes for code and tests

**Pull request merged**
